server:
  port: 8188
spring:
  application:
    name: springboot3withdb23c
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      jdbc-url: jdbc:oracle:thin:@192.168.31.23:1521/pdb1
      username: hr
      password: oracle
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: false
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    cache: false
logging:
  level:
    root: error
    com:
      oracle:
        db23c: info

