server:
  port: 8181
spring:
  cassandra:
    keyspace-name: db23c
    schema-action: recreate
    local-datacenter: datacenter1
logging:
  level:
    root: info
    org.springframework.data.mongodb.core: debug
