server:
  port: 8189
spring:
  application:
    name: springboot3withdb23
  boot:
    admin:
      client:
        url: http://localhost:8188
        username: admin
        password: oracle
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
    com:
      oracle:
        db23c: info
