server:
  port: 8188
spring:
  application:
    name: springboot3withdb23c
  kafka:
    bootstrap-servers:
      - 192.168.31.45:9092
    template:
      default-topic: employee.topic
    producer:
#      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
#      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.oracle.db23c.po
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
    com:
      oracle:
        db23c: info
