
CREATE TABLE ratings (
  REVIEW_ID INT NOT NULL,
  RATING INT,
  PRIMARY KEY (REVIEW_ID)
);
INSERT INTO ratings (REVIEW_ID, RATING) VALUES (1, 5);
INSERT INTO ratings (REVIEW_ID, RATING) VALUES (2, 4);
COMMIT;